version: '3'

services:
  web:
    build:
      context: ./app_web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app_web/bdd.txt:/app/bdd.txt
    networks:
      - auth_network
    depends_on:
      - encryption

  encryption:
    build:
      context: ./encryption_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge 